### ISSUE TITLE
Why not use rnpm install in the documentation?

### ISSUE THREAD

**Issue by PimDeWitte** [davecoates/rn-firebase-bridge#1]
Hey Dave!

App seems to work fine when using rnpm install rn-firebase-bridge

Any reason why this is not listed in the docs?

Thanks!

**Comment by davecoates** [comment]
Hi there

I didn't actually know about that command but reading the doc's it looks like it is literally the same as doing a `npm install` and `rnpm link` so is the equivalent of what is there. I'll update the doc's shortly to mention it - thanks!
