### ISSUE TITLE
Can't get error codes from Auth

### ISSUE THREAD

**Issue by jaimecorrea** [davecoates/rn-firebase-bridge#10]
I'm trying to get error codes from Auth API to handle them, but I just get a the error message and it's not as it's in the API reference [here](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithEmailAndPassword).

Code: 
```
signInWithEmail(value.email, value.password).then(
        user => {
          //do something
        },
        error => {
          console.log(error);
          console.log(error.code);
          console.log(error.message);
```

Result:
> Error: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The password is invalid or the user does not have a password.(…)
> EUNSPECIFIED
> NewUser.js:88 com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The password is invalid or the user does not have a password.

**Comment by davecoates** [comment]
Thanks I've sorted that out on Android - just need to do it for iOS and I'll push a new release with the fix

**Comment by jaimecorrea** [comment]
Great!! Could you tell me how to update this commit in my project using npm? or should I use git?

Thanks!

**Comment by davecoates** [comment]
You should just be able to install new version from npm

`npm install rn-firebase-bridge@0.0.6 --save`
