### ISSUE TITLE
No support for auth().signInWithCredential()?

### ISSUE THREAD

**Issue by Victoor** [davecoates/rn-firebase-bridge#12]
I want to sign up an user using a Facebook token. It's possible with this library?

Thanks,

**Comment by davecoates** [comment]
Currently no but seems straightforward, I'll look at adding it soon

**Comment by davecoates** [comment]
I've added support for iOS but only tested Facebook, other providers should work though

Will look at Android soon

**Comment by Victoor** [comment]
Thanks. This looks promising! 👍
