### ISSUE TITLE
Can't close the connection in snapshot

### ISSUE THREAD

**Issue by jaimecorrea** [davecoates/rn-firebase-bridge#21]
I'm not able to close the connection with "snapshot", so it keeps returning (even if I return true to the promise promise). My code:

```
            const ref = db.child('User').child(user.uid);
            var user = null;

            ref.on('value', async (snapshot) => {

              user = await snapshot.val();

              console.log(user);

              return true;

            });

          }
```

**Comment by davecoates** [comment]
Do you mean that you only want the listener called once? `ref.on` returns a function you can use to remove the listener or alternatively use `ref.once` which only gets called once.

**Comment by davecoates** [comment]
Closing this now but feel free to re-open it if I misunderstood
