### ISSUE TITLE
Handling errors in once method

### ISSUE THREAD

**Issue by Paul-Todd** [davecoates/rn-firebase-bridge#25]
Should the "func on" and "func once" methods have "withCancelBlock" extensions in their "observeSingleEventOfType"/ "observeEventType" helpers.

I got a promise being unfulfilled because the backend was returning permission denied and it was not being handled because the "withBlock" was not called.

**Comment by Paul-Todd** [comment]
For now I have fixed the permissions problem on the backend but there are other cases I can think of where the response could be interrupted and would need handling.

**Comment by davecoates** [comment]
Ah yes - you are correct

Will have a fix soon

**Comment by davecoates** [comment]
Available 0.1.1
