### ISSUE TITLE
Google auth

### ISSUE THREAD

**Issue by ajonno** [davecoates/rn-firebase-bridge#26]
hi, firstly thanks for publishing this react native api for Firebase. will save us time thats for sure!

sorry to post this question here - but could you possibly provide an example of Google auth ? 
```
async signInWithGoogle(idToken, accessToken) {...
```
What Im struggling with is how, in the case of Google auth, to get the idToken and accessToken ?  does being a fellow aussie(!) help ? ;-) appreciate any assistance u can lend on this.

**Comment by davecoates** [comment]
Hi Angus,

Sorry, I don't have an example but you could have a look at:

https://github.com/devfd/react-native-google-signin

I haven't used it but looks like it gives you all you need to get the token(s) you need to then pass to the `signInWithGoogle` function. A cursory glance over it and the Firebase SDK indicates that accessToken is only needed for iOS, for Android it can be null. 

Hope that helps!

**Comment by ajonno** [comment]
no worries somehow i missed that google auth repo but its perfect, many thanks
