### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by jaimecorrea** [davecoates/rn-firebase-bridge#27]
Error after react-native run-ios

**Comment by davecoates** [comment]
Can you provide more details? A stack trace?

**Comment by jaimecorrea** [comment]
I'm not able to run my app on iOS, on Android works fine... the error trace goes to the import of rn-firebase-bridge

**Comment by jaimecorrea** [comment]
![captura de pantalla 2016-12-21 a las 11 59 01 a m](https://cloud.githubusercontent.com/assets/18601530/21398315/ef4ed522-c774-11e6-90d9-b8251448bf15.png)

**Comment by jaimecorrea** [comment]
I can't manage to link Libraries on xCode Project, If I just select the folder "ios" I can't define the "Objective-C Bridging Header", but if I select the files inside "ios" folder, I got the error "Native Module cannot be null".

**Comment by jaimecorrea** [comment]
`node_modules/rn-firebase-bridge/ios/FirebaseBridgeApp.swift:64:24: error: boolean condition requires 'where' to separate it from variable binding
    if let name = name , name != "" {
                       ^
                        where


** BUILD FAILED **



The following build commands failed:

	CompileSwift normal x86_64 /Users/DIANA/Code/test/AwesomeProject/node_modules/rn-firebase-bridge/ios/FirebaseBridgeGoogleAuthProvider.swift

	CompileSwift normal x86_64 /Users/DIANA/Code/test/AwesomeProject/node_modules/rn-firebase-bridge/ios/FirebaseBridgeTwitterAuthProvider.swift

	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

(3 failures)
`

**Comment by davecoates** [comment]
Ah... probably new swift version 

If possible could you try under Build Settings setting "Use Legacy Swift Language Version" to Yes?

**Comment by jaimecorrea** [comment]
I did it and I got this:
`Switch must be exhaustive, consider adding a default clause` in FirebaseBridgeAuth.swift...

Therefore, I had to add the "default clause" and finally it run ok...

Thanks!
