### ISSUE TITLE
Can't find Objective-C Bridging Header in xCode

### ISSUE THREAD

**Issue by jaimecorrea** [davecoates/rn-firebase-bridge#28]

**Comment by davecoates** [comment]
Is there an error here? You have the "Object-C Bridging Header" set to a file that exists in your project?

**Comment by jaimecorrea** [comment]
"Object-C Bridging Header" only appears in xCode when I add the swift files directly to Libraries, not if I add "ios" folder... after that, it is possible to set the "Object-C Bridging Header"
