### ISSUE TITLE
iOS version is not working at the moment

### ISSUE THREAD

**Issue by PimDeWitte** [davecoates/rn-firebase-bridge#3]
<img width="399" alt="screen shot 2016-07-01 at 10 35 08 am" src="https://cloud.githubusercontent.com/assets/8763534/16529399/856e130a-3f77-11e6-8824-a0d6c5fff69b.png">

So I'm assuming rnpm install only links android at the moment, not iOS?

Can you put some further documentation on how to create the swift header file and run through the iOs setup? Can't seem to get it to work.

**Comment by davecoates** [comment]
Sorry about that - can you try this?

Create a new header file by  choosing File > New > File > (iOS) > Source > Header File and naming something like <Appname>-Bridging-Header.h.

Next go to Build Settings and under Swift Compiler - Code Generation, set the `Objective-C Bridging Header` build setting to ` <Appname>-Bridging-Header.h`.

That *should* be it.

Unfortunately `rnpm link` doesn't work for this as Xcode doesn't support generating static libraries that include Swift code.

Could you try the above and let me know how you go and I'll update the readme accordingly?

**Comment by PimDeWitte** [comment]
So, I tried this from the same link you're getting it from, and it didn't work. Here's what I ended up doing:
<img width="693" alt="screen shot 2016-07-02 at 8 11 14 am" src="https://cloud.githubusercontent.com/assets/8763534/16540988/8fef49d8-402c-11e6-942d-9f9b7dbb055c.png">

The problem seems to be in linking the library. When I created the bridging header and drop the files in the project repo, and then reference them, it works fine.

**Comment by davecoates** [comment]
Does that mean you have copied the files into your project? That will make it annoying for you to update - here's what I've done on a new project I created to test this:

![image](https://cloud.githubusercontent.com/assets/1896376/16543040/1c46ac7c-4105-11e6-903e-e811093e608e.png)

where the FirebaseBridge directory was added as per the readme and then renamed from `ios` to `FirebaseBridge`.
