### ISSUE TITLE
Could not invoke FirebaseBridgeDatabase.ref

### ISSUE THREAD

**Issue by jaimecorrea** [davecoates/rn-firebase-bridge#30]
Android
React 15.4.1
React Native 0.39.2

![screenshot_20161226-102010](https://cloud.githubusercontent.com/assets/18601530/21483962/dada232a-cb58-11e6-8373-4c36db5f8251.png)

I already did all the setup for android, it worked fine for Android and iOS until I upgraded to RN 0.39.2

**Comment by davecoates** [comment]
Could you provide a way to reproduce? I've tried the [testapp](https://github.com/davecoates/rn-firebase-bridge/tree/master/tests/testapp) with RN 0.39.2 on Android and seems to work fine

**Comment by jaimecorrea** [comment]
I just upgrade to RN 0.39.2... what kind of info should I send you?

**Comment by davecoates** [comment]
Is it a particular use of `database.ref()` in your JS that triggers the problem? Are you able to track it down to the JS code the triggers the error?

**Comment by jaimecorrea** [comment]
It is working fine on iOS with the same code... how can I track the issue in Android?

**Comment by davecoates** [comment]
I assume you ran `react-native upgrade` - did it replace your `MainApplication.java` and `android/settings.gradle`? See if `MainApplication.java` still includes `new FirebaseBridgePackage()` and `settings.gradle`:

```
include ':rn-firebase-bridge', ':app'
project(':rn-firebase-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/rn-firebase-bridge/android')
```

You might be able to run `react-native link` if this is the problem

**Comment by jaimecorrea** [comment]
I have checked everything and I still get the error...

**Comment by davecoates** [comment]
I'm going to close this but if you are still having problems feel free to re-open
