### ISSUE TITLE
setPersistenceEnabled is not working

### ISSUE THREAD

**Issue by PimDeWitte** [davecoates/rn-firebase-bridge#4]
![screen shot 2016-07-06 at 7 44 49 pm](https://cloud.githubusercontent.com/assets/8763534/16641089/215186e2-43b2-11e6-983c-21e7e7945681.png)

<img width="497" alt="screen shot 2016-07-06 at 7 45 06 pm" src="https://cloud.githubusercontent.com/assets/8763534/16641090/27a8968e-43b2-11e6-8ba6-74511363e779.png">

**Comment by davecoates** [comment]
I'll try look at this later today..

In the meantime could you try moving the code under `Database.setPersistenceEnabled(true)` into `componentWillMount` on your root component and see if that changes anything? (leave the setPersistenceEnabled where it is)

I'm assuming this is Android?

**Comment by PimDeWitte** [comment]
Actually was iOS. By the way, Firebase released this today, might be worth
looking into:
https://firebase.googleblog.com/2016/07/firebase-react-native.html

On Wed, Jul 6, 2016 at 8:17 PM, Dave Coates <notifications@github.com>
wrote:

> I'll try look at this later today..
>
> In the meantime could you try moving the code under
> Database.setPersistenceEnabled(true) into componentWillMount on your root
> component and see if that changes anything? (leave the
> setPersistenceEnabled where it is)
>
> I'm assuming this is Android?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davecoates/rn-firebase-bridge/issues/4#issuecomment-230968667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIW4jucu910urfozx0ukDkBSEH0jV0h-ks5qTG-3gaJpZM4JGsFo>
> .
>



-- 


CEO & Founder at Whitespell
Web: http://whitespell.com Tel: +1 786 201 9489
Whitespell, 350 Lincoln Rd Floor 2, Miami, FL 33139

**Comment by davecoates** [comment]
Moving the database interaction to `componentWillMount()` fixes it for the initial load.

However every time you refresh it will try to enable it again which will cause issues because the database will have been used. I'll need to change it to only do the persistence call once.

Changing this in `FirebaseBridgeDatabase.swift` should make it work:

```
@objc func setPersistenceEnabled(enabled:Bool) {
    if (FIRDatabase.database().persistenceEnabled != enabled) {
      FIRDatabase.database().persistenceEnabled = enabled
    }
  }
```
--

Thanks for the heads up on that blog post, I'll have a look.
