### ISSUE TITLE
getRefFromUrl in FirebaseBridgeDatabase handling of empty databaseUrl string issue

### ISSUE THREAD

**Issue by pietgk** [davecoates/rn-firebase-bridge#6]
I added a check for empty string while trying out some code:

```
  func getRefFromUrl(databaseUrl: String?) -> FIRDatabaseReference {
    if let url = databaseUrl {
      if url.isEmpty {
        return FIRDatabase.database().reference()
      } else {
        return FIRDatabase.database().referenceFromURL(url)
      }
    }
    return FIRDatabase.database().reference()
  }
```

it got my testing working :-)

regards Piet

**Comment by davecoates** [comment]
Thanks!

What was the JS code that triggered it? Just when passing empty string to `child()`, or something else?

**Comment by pietgk** [comment]
Database.ref() triggered it.

**Comment by davecoates** [comment]
Database.ref() itself doesn't actually result in any calls to the native code, it's only once you do something like `child` that something occurs. 

I've tried to make it happen without much luck - your fix looks fine but I'm curious as to when it's actually needed

**Comment by davecoates** [comment]
Ah nevermind, found it. Thanks!
